name: YAF.NET v4 (.NET v9)
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
        node-version: [latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Packages
        working-directory: ./yafsrc/YetAnotherForum.NET
        run: npm install
      - name: Build
        working-directory: ./
        run: dotnet build ./yafsrc/YAF.NET-SqlServer.slnx
      - name: Test
        working-directory: ./
        run: dotnet test ./yafsrc/YAF.NET-SqlServer.slnx